baseurl: https://bobbryson.netlify.app
languageCode: en-us
theme: hugo-theme-stack-personal
paginate: 5
title: Bob Bryson's Blog

# Change it to your Disqus shortname before using
disqusShortname: sleepypapi

# GA Tracking ID
googleAnalytics: G-M8F61NWWZR

# Enable emoji support
enableEmoji: true

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 😎
        subtitle: Frank and opinionated. Brace yourself. Cheers! 🍻
        avatar:
            enabled: true
            local: false
            src: https://i.imgur.com/2Ood6S6.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Copyrighted under Moriasi Bob Bryson.

    comments:
        enabled: true
        provider: waline

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL: https://waline-commenting-system.vercel.app
            lang: en-US
            visitor: false
            avatar: mp
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email

            locale:
                admin: Admin
                placeholder: Enter your comment over here...

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: true

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
